### ISSUE TITLE
Missing dev-libs/libgcrypt-1.5.3-r100 required by media-sound/spotify-0.9.4.183-r6

### ISSUE THREAD

**Issue by chusopr** [funtoo/funtoo-overlay#41]
```
emerge: there are no ebuilds to satisfy "dev-libs/libgcrypt:11/11".
(dependency required by "media-sound/spotify-0.9.4.183-r6" [ebuild])
(dependency required by "media-sound/spotify" [argument])
```

This dev-libs/libgcrypt:11/11 dependency in Gentoo is provided by dev-libs/libgcrypt-1.5.3-r100 missing in Funtoo.

**Comment by danielrobbins** [comment]
This issue has been imported into the Funtoo Linux bug tracker. This helps us to ensure that your bug is prioritized and gets the attention it deserves. You are welcome to create a Funtoo account and participate in the Funtoo Linux workflow or follow-up in the GitHub issue (comments are not currently synchronized.) Follow the action here: https://bugs.funtoo.org/browse/FL-2009
