### ISSUE TITLE
www-client/qutebrowser: IUSE tweak

### ISSUE THREAD

**Issue by kjnirlp** [funtoo/funtoo-overlay#78]
Request something like this
`IUSE="webkit webengine"`
```
RDEPEND="
    webkit? (dev-python/PyQt5[${PYTHON_USEDEP},declarative,gui,network,printsupport,webkit,widgets])
    webengine? (dev-python/PyQt5[${PYTHON_USEDEP},declarative,gui,network,printsupport,webchannel,webengine,widgets]"
```

**Comment by danielrobbins** [comment]
This issue has been imported into the Funtoo Linux bug tracker. This helps us to ensure that your bug is prioritized and gets the attention it deserves. You are welcome to create a Funtoo account and participate in the Funtoo Linux workflow or follow-up in the GitHub issue (comments are not currently synchronized.) Follow the action here: https://bugs.funtoo.org/browse/FL-3565

**Comment by angryvincent** [comment]
idea is to use qtwebengine or qtwebkit for qutebrowser. does it support both?

**Comment by kjnirlp** [comment]
v0.9.1 works without qtwebkit

**Comment by angryvincent** [comment]
unfortunately it doesn't. It gives me me warning about no webkit module found, which has to come from PyQt5[webkit]. in 9999 ebuild webengine support is possible to add.

**Comment by kjnirlp** [comment]
Anyway I am using 9999 so it's fine to modify 9999 only and thank you for report to upstream.
Could you fork it temperarily?

**Comment by angryvincent** [comment]
i reported this already:
https://bugs.gentoo.org/show_bug.cgi?id=608820
